### ISSUE TITLE
Claims are empty

### ISSUE THREAD

**Issue by DianaLaa** [tugberkugurlu/AspNetIdentitySamples#1]
https://github.com/tugberkugurlu/AspNetIdentitySamples/blob/96051547a6d97dbd3d724f9e513ade695c930ce5/SimpleOAuthSample/SimpleOAuthSample/Controllers/UsersController.cs#L15

Hi Tugberk, thank you for your blog post and sample application.
For me, the identity.Claims are always empty when I post using my access token.
Have you seen this before? Can you advise?

**Comment by tugberkugurlu** [comment]
Hi there, sorry, just seen this now 😞 

It could be the case that authentication failed for some reason?

**Comment by DianaLaa** [comment]
No, I made a mistake: my WebAPI doesn't support cookie authentication and I was trying to use that. Instead, I had to supply my access token :)
